### PR TITLE
Fix: add pip package to install and default pg passwd from os.env

### PR DESCRIPTION
**Pull request by adamtracy**
couple small fixes here

### CODE REVIEW

**Comment by adamtracy** [comment]
OK, moved PR to this repo. Did you have plans for moving the old repo comments to this one @iamh2o ?

**Comment by iamh2o** [comment]
The ubuntu action I can get going

**Comment by iamh2o** [comment]
@adamtracy -- I got a bee in my bonnet, and decided to get Bloom to pass github tests on centos 9 (why not?!)... in doing so, I needed to pull some of the lingering weird schema stuff out (positive) and clarify bdb a little (maybe lining up more tidying passes soon... TLDR:  tests now pass on Mac/Ubuntu/Centos!   

Another thing, I do not understand, but I had to remove this pip package: `envsubst`, it was causing some postgres errors only on centos and ubuntu... not mac.

**Comment by adamtracy** [comment]
@iamh2o right on, thanks

**Pull request merged**
